#server:
#  port: 8081
#
##动态配置
#dtp:
#  executors:
#    - name: t1
#      core-pool-size: 10
#      maximum-pool-Size: 100
#    - name: t2
#      core-pool-size: 20
#      maximum-pool-Size: 110

#nacos配置
nacos:
  config:
    server-addr: 127.0.0.1:8848
    data-id: dtp.yaml
    type: yaml
    auto-refresh: true
    bootstrap:
      enable: true